---
# Bareos installation
- name: Check if Bareos has been already installed
  stat:
    path: /usr/lib/bareos/installed
  register: bareos_installed
  tags: [bareos-director]

- name: Install Bareos packages
  package:
    name: bareos, bareos-database-postgresql
    state: installed
  when: not bareos_installed.stat.exists
  tags: [bareos-director]

- name: Create PostgreSQL database
  shell: su - postgres -c '/usr/lib/bareos/scripts/create_bareos_database postgresql'
  when: not bareos_installed.stat.exists
  tags: [bareos-director]

- name: Create initial PostgreSQL tables
  shell: su - postgres -c '/usr/lib/bareos/scripts/make_bareos_tables postgresql'
  when: not bareos_installed.stat.exists
  tags: [bareos-director]

- name: Grant PostgreSQL user privileges
  shell: su - postgres -c '/usr/lib/bareos/scripts/grant_bareos_privileges postgresql'
  when: not bareos_installed.stat.exists
  tags: [bareos-director]

- name: Change database type to PostgreSQL for catalog resource
  lineinfile:
    path: "{{ bareos_config_dir }}/bareos-dir.d/catalog/MyCatalog.conf"
    regexp: "dbdriver = .*"
    line: "dbdriver = postgresql"
  when: not bareos_installed.stat.exists
  tags: [bareos-director]

- name: Enable and start Bareos services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - 'bareos-dir'
    - 'bareos-sd'
    - 'bareos-fd'
  tags: [bareos-director]

# Remote storages configuration
- name: Configure storage locations in {{ bareos_config_dir }}/bareos-dir.d/storage/*.conf (Director)
  template:
    src: "director/storage.conf.j2"
    dest: "{{ bareos_config_dir }}/bareos-dir.d/storage/{{ item.name }}.conf"
    owner: "{{ bareos_user_name }}"
    group: "{{ bareos_group_name }}"
    mode: 0640
  loop: "{{ bareos_remote_storages }}"
  notify: reload bareos-dir
  tags: [bareos-director, bareos-director-reconfigure, bareos-storage]

# Local storage configuration
- name: Configure local {{ bareos_config_dir }}/bareos-sd.d/director/bareos-dir.conf (Director)
  template:
    src: "director/bareos-dir.conf.j2"
    dest: "{{ bareos_config_dir }}/bareos-sd.d/director/bareos-dir.conf"
    owner: "{{ bareos_user_name }}"
    group: "{{ bareos_group_name }}"
    mode: 0640
  notify: restart bareos-sd
  tags: [bareos-director, bareos-director-reconfigure, bareos-storage]

# Other director configuration, related to jobs, schedules
- name: Configure messages in {{ bareos_config_dir }}/bareos-dir.d/messages/Standard.conf
  template:
    src: "director/messages-standard.conf.j2"
    dest: "{{ bareos_config_dir }}/bareos-dir.d/messages/Standard.conf"
    owner: "{{ bareos_user_name }}"
    group: "{{ bareos_group_name }}"
    mode: 0640
  notify: reload bareos-dir
  tags: [bareos-director, bareos-director-reconfigure]

- name: Configure filesets in {{ bareos_config_dir }}/bareos-dir.d/fileset/*.conf (Director)
  template:
    src: "director/filesets.conf.j2"
    dest: "{{ bareos_config_dir }}/bareos-dir.d/fileset/{{ item.name }}.conf"
    owner: "{{ bareos_user_name }}"
    group: "{{ bareos_group_name }}"
    mode: 0640
  loop: "{{ bareos_filesets }}"
  notify: reload bareos-dir
  tags: [bareos-director, bareos-director-reconfigure]

- name: Configure schedules in {{ bareos_config_dir }}/bareos-dir.d/schedule/*.conf (Director)
  template:
    src: "director/schedules.yml.j2"
    dest: "{{ bareos_config_dir }}/bareos-dir.d/schedule/{{ item.name }}.conf"
    owner: "{{ bareos_user_name }}"
    group: "{{ bareos_group_name }}"
    mode: 0640
  loop: "{{ bareos_schedules }}"
  notify: reload bareos-dir
  tags: [bareos-director, bareos-director-reconfigure]
