---
# OS-specific vars
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      skip: true

# Setup/install tasks.
- include_tasks: setup-repositories.yml
