---
# OS-specific vars
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      skip: true

# Setup/install tasks.
- include_tasks: setup-repositories.yml

# Director-specific tasks
- include_tasks: bareos-director.yml
  when: groups.bareos_director[0] in inventory_hostname
  tags: [bareos-director]

- include_tasks: bareos-storage.yml
  loop: "{{ groups[bareos_clients_group_name] }}"
  when: item in inventory_hostname
  tags: [bareos-storage]

# Client tasks.
- include_tasks: bareos-client.yml
  when: groups.bareos_director[0] not in inventory_hostname
  tags: [bareos-client]
