---
# OS-specific vars
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [bareos-director, bareos-director-reconfigure, bareos-storage, bareos-client, bareos-add-client]

- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      skip: true
  tags: [bareos-director, bareos-director-reconfigure, bareos-storage, bareos-client, bareos-add-client]

# Setup/install tasks.
- include_tasks: setup-repositories.yml
  tags: [bareos-client, bareos-add-client]

# Director-specific tasks
- include_tasks: bareos-director.yml
  when: groups.bareos_director[0] in inventory_hostname
  tags: [bareos-director, bareos-director-reconfigure, bareos-storage]

# WebUI tasks
- include_tasks: bareos-webui.yml
  when: >
    groups.bareos_director[0] in inventory_hostname and
    bareos_webui_enabled
  tags: [bareos-webui] 

# Storages tasks
- include_tasks: bareos-storage.yml
  loop: "{{ groups[bareos_storages_group_name] }}"
  when: item in inventory_hostname
  tags: [bareos-storage]

# Client tasks
- include_tasks: bareos-client.yml
  when: >
    groups.bareos_director[0] not in inventory_hostname and
    bareos_storages_group_name not in group_names
  tags: [bareos-client, bareos-add-client]
