---
- name: restart bareos-fd
  service:
    name: bareos-fd
    state: restarted

- name: reload bareos-dir
  shell: "echo reload | bconsole"
  delegate_to: "{{ groups.bareos_director[0] }}"
  run_once: True
